### ISSUE TITLE
RN Android "0.63.4 App Crash

### ISSUE THREAD

**Issue by michaelVictoriaDev** [tinycreative/react-native-intercom#441] opened 2021-05-05 04:12 UTC
After config all in the docs, and config the gradle.

```
 ext {
        buildToolsVersion = '29.0.2'
        minSdkVersion = 26
        compileSdkVersion = 29
        targetSdkVersion = 29
    }
```

Im having app crash with no errors in my terminal

Then Im starting to check in adb logs , I think the screenshot is saying there's an error in the package.

![image](https://user-images.githubusercontent.com/44763288/117096182-e399ac00-ad9a-11eb-88ae-d3a453335781.png)

**Comment by oneji** [comment] 2021-05-16 18:59
I have the same issue!

**Comment by molimat** [comment] 2021-05-28 18:12
I am having an issue like this as well. In my case after just follow up the installation guide, suddenly all my axios requests are returning Network Error and they were just fine before.

**Comment by akshayLuthraDev** [comment] 2021-06-01 21:44
Hi, I also faced a similar situation when using the updated version 21.1.0 (or even 20.0.0). It was running successfully on Android only when I run the app in Debug mode and ENABLE the Network Inspect otherwise the Android app is always crashing as soon as a Network call is made.

**Comment by akshayLuthraDev** [comment] 2021-06-01 21:54
I also faced similar issue when using the updated version 21.1.0 (or even 20.0.0). 
It was running successfully on Android only when I run the app in Debug mode and ENABLE the Network Inspect otherwise the Android app was always crashing as soon as a Network call was hit.

A quick fix for the issue is to downgrade the package to **^18.0.0** and use sdk **7.+** . By using this configuration, Android app won’t crash in release mode but the UI of Intercom screen looks distorted. 

Seems like we have to wait to get the latest version of the package fixed to make everything work properly.

**Comment by akshayLuthraDev** [comment] 2021-06-01 21:59
Refer this issue thread for details on fixing the crash : https://github.com/tinycreative/react-native-intercom/issues/422

**Comment by molimat** [comment] 2021-06-01 22:11
We did fix this updating the okhttp packages in our gradlew, for some reason Intercom and some other libraries were trying to make requests using different okhttp versions, causing crash. Not sure if everyone is having the same issue, but my fix was adding these lines:

`dependencies {
       // define a BOM and its version
implementation(platform("com.squareup.okhttp3:okhttp-bom:4.9.0"))
       // define any required OkHttp artifacts without version
       implementation("com.squareup.okhttp3:okhttp")
       implementation("com.squareup.okhttp3:logging-interceptor")
    }`

**Comment by akshayLuthraDev** [comment] 2021-06-02 12:11
Thanks @molimat ! Your solution works like a charm.

**Comment by shanimol** [comment] 2021-06-29 11:25
We also faced same crash issue with react native insider versions greater than 19.0.0. The above fix mentioned by @molimat fixed the crash issue, but was causing some problems with  other libraries already there in our app. So that didn't help us. 

Waiting for a permanent fix for this crash problem.

**Comment by daniel-moya** [comment] 2021-08-20 12:44
Thanks to @molimat , this solution works!

Also you can check the OkHttp docs where you can find the examples @molimat mentioned

https://square.github.io/okhttp/#releases

```
    dependencies {
       // Intercom requires okhttp packages to be version compatible
       // For latest release please check: https://square.github.io/okhttp/#releases
       // define a BOM and its version
       implementation(platform("com.squareup.okhttp3:okhttp-bom:4.9.0"))

       // define any required OkHttp artifacts without version
       implementation("com.squareup.okhttp3:okhttp")
       implementation("com.squareup.okhttp3:logging-interceptor")
    }
```

**Closed as completed** 2021-12-09 23:50 UTC
